version: '3'
services:
    add:
        build: 
            context: .
            dockerfile: 
                ./images/service.Dockerfile
            args:
                TYPE: add
    subtract:
        build: 
            context: .
            dockerfile: 
                ./images/service.Dockerfile
            args:
                TYPE: subtract
    multiply:
        build: 
            context: .
            dockerfile: 
                ./images/service.Dockerfile
            args:
                TYPE: multiply
    divide:
        build: 
            context: .
            dockerfile: 
                ./images/service.Dockerfile
            args:
                TYPE: divide
        
